export const USER_STRINGS = {
  common: {
    appNameShort: 'KDKMP SHU',
    appNameFull: 'KDKMP Banguntapan Bantul',
    appTagline: 'Sistem Sisa Hasil Usaha Anggota',
    tryAgain: 'Coba lagi',
    okay: 'Oke',
    yes: 'Ya',
    no: 'Tidak',
    cancel: 'Batal',
    loading: 'Memuat...',
    save: 'Simpan',
    close: 'Tutup',
    back: 'Kembali',
    next: 'Selanjutnya',
    submit: 'Kirim',
    show: 'Tampilkan',
    hide: 'Sembunyikan',
    copied: 'Disalin',
    required: 'Wajib diisi',
    comingSoon: 'Segera hadir',
    fiscalYear: 'Tahun Buku',
    loadingErrorTitle: 'Gagal memuat data',
    somethingWrongTitle: 'Terjadi kendala',
    emptyStateDefaultTitle: 'Belum ada data',
  },
  onboarding: {
    skipButton: 'Lewati',
    stepIndicatorOf: (now: number, total: number) => `${now} dari ${total}`,
    slide1: {
      title: 'Selamat datang di KDKMP SHU',
      description:
        'Aplikasi resmi untuk Partisipasi Rapat Anggota Tahunan & pembagian Sisa Hasil Usaha (SHU) Koperasi KDKMP di ponsel Anda.',
      illustrationCta: 'Aplikasi Resmi Koperasi',
    },
    slide2: {
      title: 'Alur Voting SHU, Langkah demi Langkah',
      description:
        '1️⃣ Masukkan NIK KTP 16 digit → 2️⃣ Verifikasi OTP WhatsApp → 3️⃣ Baca Laporan Keuangan → 4️⃣ Pilih Setuju/Tidak Setuju → 5️⃣ Selesai',
      illustrationCta: '5 Langkah Super Mudah',
    },
    slide3: {
      title: 'Aturan Penting Wajib Tahu',
      description:
        '✅ 1 NIK = HANYA 1 SUARA per tahun buku · ⚠️ Pilihan SUDAH dikirim TIDAK BISA diubah · 🔒 Pilihanmu RAHASIA & tidak bisa dilacak siapa pun. Suara Anda menentukan pembagian SHU yang ADIL.',
      illustrationCta: 'Pahami dulu sebelum mulai!',
    },
    finalCta: 'Masuk dengan NIK',
  },
  nationalIdLogin: {
    pageTitle: 'Masuk Akun Anggota',
    pageSubtitle: 'Gunakan NIK KTPmu untuk masuk ke akun anggota KDKMP.',
    inputLabel: 'Nomor Induk Kependudukan (NIK)',
    inputPlaceholder: 'Masukkan 16 digit NIK',
    inputHelper: 'Pastikan NIK 16 digit sesuai KTP. NIK tidak disimpan di aplikasi.',
    ctaSubmit: 'Kirim Kode OTP',
    ctaSubmitLoading: 'Mengirim kode...',
    nikMaskedTag: 'NIK',
    needHelp: 'Butuh bantuan?',
    helpContact: 'Hubungi pengurus koperasi',
    policy: 'Dengan melanjutkan, kamu menyetujui syarat & kebijakan privasi KDKMP.',
  },
  otpVerification: {
    pageTitle: 'Masukkan Kode OTP',
    pageSubtitlePrefix: 'Kode 6 digit dikirim ke WhatsApp',
    inputPlaceholder: '•',
    ctaSubmit: 'Verifikasi',
    ctaSubmitLoading: 'Memverifikasi...',
    resendAvailable: 'Kirim ulang kode',
    resendCountdown: (human: string) => `Kirim ulang dalam ${human}`,
    resendRemaining: (mmss: string) => `Sisa masa berlaku: ${mmss}`,
    wrongOtpOnce: 'Kode OTP salah. Coba cek lagi ya.',
    wrongOtpLocked: (waitText: string) => `Terlalu banyak salah. Tunggu ${waitText} sebelum coba lagi.`,
    otpExpired: 'Kode OTP sudah kadaluarsa. Silakan kirim ulang.',
    infoPrivacy:
      'Kode OTP hanya untuk verifikasi pemilik NIK. Jangan berikan kode ini kepada siapa pun, termasuk pihak koperasi.',
    wrongDestination: 'Bukan WhatsApp saya',
  },
  dashboard: {
    greetingMorning: 'Selamat pagi',
    greetingDay: 'Selamat siang',
    greetingEvening: 'Selamat sore',
    greetingNight: 'Selamat malam',
    greetingAnonymous: 'Halo',
    greetingSuffix: ', semoga sehat selalu ya 👋',
    settingsCta: 'Pengaturan & Keluar',
    logoutCta: 'Keluar',
    tabVoting: 'Voting',
    tabReports: 'Laporan',
    tabProfile: 'Profil',
    sectionShuAmount: 'Jumlah SHU',
    sectionMemberData: 'Data Anggota',
    sectionCooperativeData: 'Data KDKMP',
    sectionReports: 'Laporan Keuangan',
    fabVotingLabel: 'Mulai Voting',
    votingVotedTabHint: 'Kamu sudah memberikan suara. Cek tab Laporan atau Profil untuk data lainnya.',
    profitSharingCardTitle: (year: number) => `SHU Tahun Buku ${year}`,
    profitSharingCardSubtitle: 'Jumlah yang dibagikan ke seluruh anggota',
    profitSharingCardStatusOpen: 'Masa voting berlangsung',
    profitSharingCardStatusVoted: 'Terima kasih, suara kamu sudah terekam',
    profitSharingCardStatusApproved: 'Sudah disetujui Rapat Anggota',
    profitSharingCardStatusDistributed: 'Sudah dibagikan ke rekening anggota',
    votingSectionTitle: 'Pemungutan Suara SHU',
    votingSectionSubtitle:
      'Satu anggota memiliki satu hak suara untuk persetujuan pembagian SHU tahun buku ini.',
    votingInstruction:
      'Pilihanmu rahasia & tidak bisa diubah setelah dikirim. Pastikan kamu membaca laporan terlebih dahulu ya.',
    votingLegalBasisLabel: 'Dasar Hukum',
    votingLegalBasisUrl: 'https://www.peraturan.go.id/id/uu-no-25-tahun-1992',
    voteAgree: 'Setuju',
    voteDisagree: 'Tidak Setuju',
    voteCtaSubmit: 'Kirim Suara Saya',
    voteCtaChoose: 'Pilih salah satu',
    voteConfirmDialogTitle: 'Kirim suara sekarang?',
    voteConfirmDialogBody:
      'Setelah dikirim, pilihanmu tidak bisa dibatalkan ataupun diubah. Pilihanmu akan disimpan secara anonim.',
    voteConfirmDialogConfirm: 'Ya, Kirim Suara',
    profileCardTitle: 'Data Anggota',
    profileCardSubtitle: 'Data diri terdaftar di KDKMP',
    infoTabMonthly: 'Bulanan',
    infoTabYearly: 'Tahunan',
    monthlyStatementTitle: 'PNL Bulanan',
    monthlyStatementPeriod: 'Periode',
    monthlySavingsIn: 'Simpanan Masuk',
    monthlyLoanOut: 'Pinjaman Cair',
    monthlyLoanIn: 'Angsuran Masuk',
    monthlyRevenue: 'Pendapatan',
    monthlyExpenses: 'Biaya Operasional',
    monthlyNetProfit: 'Laba Bersih',
    pnlHeaderAccountName: 'Nama Akun',
    pnlHeaderNominal: 'Nominal (Rp)',
    pnlSectionRevenue: 'PENDAPATAN USHA',
    pnlRevenueRetail: 'Pendapatan Retail',
    pnlRevenueClinic: 'Pendapatan Klinik',
    pnlRevenueRental: 'Pendapatan Sewa',
    pnlRevenueConsignment: 'Penjualan Product Konsinyasi Lokal',
    pnlRevenueTotal: 'Total Pendapatan Usaha',
    pnlSectionHpp: 'HPP',
    pnlHppCogs: 'Harga Pokok Penjualan',
    pnlHppOverhead: 'Biaya Overhead',
    pnlHppOperational: 'Biaya Operasional',
    pnlHppOther: 'Biaya Hpp Lain-lain',
    pnlHppLocalSupplierLoss: 'Beban Kerugian Lokal Supplier',
    pnlHppDamagedLoss: 'Beban Kerugian Rusak',
    pnlHppLostLoss: 'Beban Kerugian Kehilangan',
    pnlHppTotal: 'Total HPP',
    pnlSectionOperatingExpenses: 'BEBAN OPERASIONAL',
    pnlOpExpGeneralAdmin: 'Beban Umum dan administrasi',
    pnlOpExpTotal: 'Total Beban Operasional',
    pnlSectionOtherIncome: 'PENDAPATAN LAIN-LAIN',
    pnlOtherIncomeCashOverage: 'Selisih Kas Lebih',
    pnlOtherIncomeMisc: 'Pendapatan Lain-lain',
    pnlOtherIncomeTotal: 'Total Pendapatan Lain-lain',
    pnlSectionOtherExpenses: 'BEBAN LAIN-LAIN',
    pnlOtherExpIncomeTax: 'PPh Final',
    pnlOtherExpCashShortage: 'Selisih Kas Kurang',
    pnlOtherExpTotal: 'Total Beban Lain-lain',
    pnlCtaDetail: 'Detail Laporan',
    pnlCtaDownloadPdf: 'Unduh PDF',
    pnlCtaDownloading: 'Membuat PDF…',
    pnlDownloadTitle: 'Laporan Keuangan Bulanan',
    pnlDownloadFooter: 'Dihasilkan otomatis melalui Aplikasi KDKMP SHU',
    shuAllocationTitle: 'Alokasi SHU',
    shuAllocationSubtitle: (year: number) => `Pembagian Sisa Hasil Usaha tahun buku ${year}.`,
    shuAllocationRevenue: 'Omset',
    shuAllocationOperatingExpense: 'Beban Usaha',
    shuAllocationNetProfit: 'Laba Bersih',
    shuAllocationApnFee: 'Fee Management APN (5%)',
    shuAllocationHoMargin: 'Margin HO',
    shuAllocationRegencyManager: 'Pengelola Kab/Kota (3%)',
    shuAllocationBoard: 'Pengurus KDKMP (15%)',
    shuAllocationMembers: 'Warga Sederhana (82%)',
    shuAllocationDownloadTitle: 'Alokasi Sisa Hasil Usaha',
    yearlySummaryTitle: 'Akumulasi Tahun Berjalan',
    yearlyPrincipalSavings: 'Simpanan Pokok',
    yearlyMandatorySavings: 'Simpanan Wajib',
    yearlyVoluntarySavings: 'Simpanan Sukarela',
    yearlyPatronage: 'Jasa Usaha (SHU Pendorong)',
    yearlyTotalShare: 'Total Bagian Anggota',
    yearlySavings: 'Simpanan',
    yearlyLoans: 'Pinjaman',
    yearlyProfitLoss: 'Laba/Rugi',
    alreadyVotedTitle: 'Kamu sudah memilih untuk tahun ini',
    alreadyVotedAgree: 'Pilihan: Setuju',
    alreadyVotedDisagree: 'Pilihan: Tidak Setuju',
    alreadyVotedSubtitle:
      'Terima kasih atas partisipasinya. Setiap suara anggota sangat berarti untuk kemajuan koperasi.',
    alreadyVotedAt: 'Waktu pilih:',
    aggregateTitle: 'Hasil Sementara Voting',
    aggregateTotal: 'Total Pemilih',
    aggregateAgree: 'Setuju',
    aggregateDisagree: 'Tidak Setuju',
    aggregateAbstain: 'Abstain',
    infoMemberId: 'No. Anggota',
    infoName: 'Nama Lengkap',
    infoNik: 'NIK',
    infoKdkmp: 'Unit KDKMP',
    infoKdkmpName: 'Nama Koperasi',
    infoKdkmpAddress: 'Alamat',
    infoKdkmpCity: 'Kabupaten / Kota',
    infoKdkmpProvince: 'Provinsi',
    infoKdkmpRegNumber: 'No. Induk Koperasi',
    infoGender: 'Jenis Kelamin',
    infoGenderMale: 'Laki-laki',
    infoGenderFemale: 'Perempuan',
    infoBirthPlaceDate: 'Tempat, Tanggal Lahir',
    infoPhone: 'No. WhatsApp',
    infoUnit: 'Unit Koperasi',
    infoProvince: 'Provinsi',
    infoCity: 'Kabupaten / Kota',
    infoDistrict: 'Kecamatan',
    infoVillage: 'Desa / Kelurahan',
    infoAddress: 'Alamat Lengkap',
    infoJoinDate: 'Tanggal Masuk',
    infoStatus: 'Status Keanggotaan',
    infoStatusActive: 'Aktif',
    infoStatusInactive: 'Tidak Aktif',
    infoStatusSuspended: 'Ditangguhkan',
    infoPrincipalSavings: 'Simpanan Pokok',
    infoMandatorySavings: 'Simpanan Wajib',
    infoVoluntarySavings: 'Simpanan Sukarela',
    infoViewMore: 'Lihat data lainnya',
    sectionAdminContact: 'Kontak Admin',
    adminContactSubtitle: 'Hubungi pengurus untuk bantuan & pertanyaan',
    sectionFaqTitle: 'Pertanyaan yang Sering Ditanyakan',
  },
  voteSuccess: {
    title: 'Suara Kamu Berhasil Dikirim!',
    subtitle:
      'Terima kasih telah berpartisipasi dalam Rapat Anggota Tahunan. Pilihanmu telah disimpan secara rahasia & anonim.',
    receiptTitle: 'Tanda Terima Suara',
    receiptToken: 'Token anonim:',
    receiptChoice: 'Pilihan:',
    receiptChoiceAgree: 'Setuju',
    receiptChoiceDisagree: 'Tidak Setuju',
    receiptTime: 'Waktu:',
    receiptYear: 'Tahun Buku:',
    ctaBackHome: 'Kembali ke Awal',
    copyTokenCta: 'Salin token',
  },
  protectedRoute: {
    redirectingLogin: 'Mengalihkan ke halaman masuk...',
  },
  gate: {
    verifyingTitle: 'Memeriksa akses...',
  },
  notFound: {
    title: 'Akses tidak ditemukan',
    description:
      'Tautan atau kode akses yang kamu gunakan tidak valid. Pastikan tautan yang dibuka sudah benar, atau hubungi pengurus koperasi untuk mendapatkan tautan akses yang sesuai.',
    ctaReload: 'Muat Ulang',
  },
  errorBoundary: {
    title: 'Ups, ada kesalahan tak terduga',
    description:
      'Tim kami sudah mendapat laporan. Silakan tutup aplikasi lalu buka kembali, atau coba muat ulang halaman ini.',
    ctaReload: 'Muat Ulang Aplikasi',
  },
} as const

export type UserStringKey = keyof typeof USER_STRINGS
