export const ErrorCode = {
  NATIONAL_ID_NOT_REGISTERED: 'NATIONAL_ID_NOT_REGISTERED',
  NATIONAL_ID_INVALID_FORMAT: 'NATIONAL_ID_INVALID_FORMAT',
  OTP_SESSION_NOT_FOUND: 'OTP_SESSION_NOT_FOUND',
  OTP_CODE_INVALID: 'OTP_CODE_INVALID',
  OTP_ATTEMPTS_EXCEEDED: 'OTP_ATTEMPTS_EXCEEDED',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_RESEND_LIMIT_EXCEEDED: 'OTP_RESEND_LIMIT_EXCEEDED',
  OTP_LOCKED_TEMPORARILY: 'OTP_LOCKED_TEMPORARILY',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_SESSION_NOT_FOUND: 'AUTH_SESSION_NOT_FOUND',
  MEMBER_PROFILE_NOT_FOUND: 'MEMBER_PROFILE_NOT_FOUND',
  VOTE_ALREADY_SUBMITTED: 'VOTE_ALREADY_SUBMITTED',
  VOTING_PERIOD_CLOSED: 'VOTING_PERIOD_CLOSED',
  PROFIT_SHARING_RECORD_NOT_FOUND: 'PROFIT_SHARING_RECORD_NOT_FOUND',
  NETWORK_ERROR: 'NETWORK_ERROR',
  UNKNOWN: 'UNKNOWN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
} as const

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode]
